Demo/urls.py
from django.contrib import admin
from django.urls import path
from application import views
from authentification import views as con_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name = "index"),
    path('prediction',views.prediction, name = "prediction"),
    path('connexion',con_views.connexion, name = "connexion"),
    path('deconnexion',con_views.deconnexion, name = "deconnexion"),
    path('inscription',con_views.inscription, name = "inscription"),
    path('monitoring',views.ma_vue_protegee_super_utilisateur, name = "Monitoring"),
    path('profile',views.profile, name = "profile")
]

application/models.py
from django.db import models

# Create your models here.

authentification/models.py
from django.db import models
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=100)
    birth_day = models.DateField()



def __str__(self):
        return self.user.username

application/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required,user_passes_test
from pymongo import MongoClient
import re
import os
from authentification.models import UserProfile
# Connexion à la base de données MongoDB
client = MongoClient("mongodb://mongoadmin:GRETA2024@vm-kaelig-mooc.francecentral.cloudapp.azure.com")
print("CLIENT",client)
db = client.Mooc
students_collection = db.message_par_user

def nombre_reussi():
    pipeline = [
        {
            "$project": {
                "notes": {
                    "$objectToArray": "$notes"
                }
            }
        },
        {
            "$unwind": "$notes"
        },
        {
            "$match": { "notes.v.certif": "Y" }
        },
        {
            "$group": {
                "_id": "$notes.k",
                "validatedCount": { "$sum": 1 }
            }
        },
        {
            "$sort": { "validatedCount": -1 }
        }
    ]

    result = students_collection.aggregate(pipeline)

    liste = []
    for element in result:
        element["id"] = re.split(r'[+/\\:]' , str(element["_id"]))  
        del element["_id"]
        liste.append(element)
    return liste

def Moyenne():
    pipeline = [
    {
        "$project": {
            "notes": {
                "$objectToArray": "$notes"
            }
        }
    },
    {
        "$unwind": "$notes"
    },
    {
        "$match": {
            "$and": [
                { "notes.v.note": { "$ne": "null" } },
                { "notes.v.note": { "$ne": "" } },
                { "notes.v.note": { "$type": "string" } }
            ]
        }
    },
    {
        "$group": {
            "_id": "$notes.k",
            "averageScore": { "$avg": { "$toDouble": "$notes.v.note" } }
        }
    },
    {
        "$project": {
            "_id": 1,
            "averageScore": { "$round": ["$averageScore", 3] } # Arrondir au deuxième chiffre
        }
    }
]

    result = students_collection.aggregate(pipeline)
    liste = []
    for element in result:
        element["id"] = re.split(r'[+/\\:]' , str(element["_id"]))
        del element["_id"]
        liste.append(element)
    return liste
   



def index(request):
    dico_url = {"CNAM01002":"https://dz03nossv7tsm.cloudfront.net/media/filer_public_thumbnails/filer_public/65/14/65149675-ff7a-42f2-85f6-573dac1b781c/fun_c-dejoux_du-manager.jpg__300x170_q85_crop-smart_subsampling-2_upscale.jpg",
                }
    liste_reussite = nombre_reussi()
    liste_moyenne = Moyenne()
    liste_affichage = []
    
    moyennes_dict = {tuple(moyenne['id']): moyenne['averageScore'] for moyenne in liste_moyenne}

    for element in liste_reussite:
        dico_affichage = {}
        id_tuple = tuple(element["id"])
        dico_affichage["id"] = element["id"]
        dico_affichage["id"][1]= dico_affichage["id"][1].split("S")[0]
        dico_affichage["validatedCount"] = element["validatedCount"]
        
        dico_affichage["averageScore"] = moyennes_dict.get(id_tuple, 0.0)  

        liste_affichage.append(dico_affichage)
    
    return render(request, "index.html", context={"liste_affichage": liste_affichage})
@login_required
def prediction(request):
    if request.method == "POST":
        message = request.POST.get("message", "")
        if message:
            return render(request, "prediction.html", {"message": message})
        else:
            message_error = "Rentrez un message pour lancer la prédiction!"
            return render(request, "prediction.html", {"message_error": message_error})
    
    # Si la requête n'est pas de type POST, renvoyer simplement la page sans message
    return render(request, "prediction.html")



def est_super_utilisateur(user):
    return user.is_superuser

@user_passes_test(est_super_utilisateur)
def ma_vue_protegee_super_utilisateur(request):
    
    return render(request, 'monitoring.html')


def profile(request):
    user = request.user  # Récupérer l'utilisateur connecté
    try:
        profile = UserProfile.objects.get(user=user)  # Récupérer le profil utilisateur associé
    except UserProfile.DoesNotExist:
        profile = None  # Gérer le cas où le profil n'existe pas

    context = {"username": user.username,
            "email": user.email,
            "first_name": user.first_name,
            "last_name": user.last_name,
            "city": profile.city if profile else None,
            "birth_day": profile.birth_day if profile else None,
            }
    return render(request, "profile.html", context)
    
            
    

authentification/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login, logout,authenticate,update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from authentification.models import UserProfile
import datetime





def connexion(request):
    message = ""
    if request.method == "POST":
        username = request.POST["username"]
        motdepasse = request.POST["motdepasse"]
        verification = authenticate(username = username,
                                    password = motdepasse)
        if verification != None:
            login(request,verification) 
            return redirect("index")
        else:
            message = "username et/ou mot de passe incorrect"
    return render(request,"connexion.html", context = {"message":message})

def deconnexion(request):
    logout(request)
    return redirect("index")





def inscription(request):
    if request.method == 'POST':
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        email = request.POST['email']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        city = request.POST['city']
        birth_day = request.POST['birth_day']
        
        try:
            birth_day =  datetime.datetime.strptime(birth_day, '%Y-%m-%d').date()
        
        except ValueError:
            error_message = "Le format de la date de naissance n'est pas valide. Utilisez le format AAAA-MM-JJ."
            return render(request, 'inscription.html', {'error_message': error_message})
        if password1 == password2:
            if not User.objects.filter(username=username).exists():
                if not User.objects.filter(email=email).exists():
                    user = User.objects.create_user(
                        username=username,
                        password=password1,
                        email=email,
                        first_name=first_name,
                        last_name=last_name
                        
                    )
                    
        
                    # Créer un profil UserProfile associé à l'utilisateur
                    profile = UserProfile.objects.create(
                            user=user,
                            city=city,
                            birth_day=birth_day
                            
                    )
                    
                    user = authenticate(username=username, password=password1)
                    return redirect('connexion')
                else:
                    error_message = "L'email est déjà utilisé"
            else:
                error_message = "Le nom d'utilisateur est déjà pris"
        else:
            error_message = "Les mots de passe ne correspondent pas"
        
        return render(request, 'inscription.html', {'error_message': error_message})
    return render(request, 'inscription.html')
    
    

def home(request):
    return render(request, 'index.html')

application/templates/architechture.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>PrédiSchool</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body {font-family: "Lato", sans-serif}
        .mySlides {display: none}
        .scroll-container {
            display: flex;
            overflow-x: auto;
            white-space: nowrap;
            margin: 0 -16px;
        }
        .scroll-item {
            display: inline-block;
            flex: 0 0 300px;
            margin: 0 8px;
            box-sizing: border-box;
        }
        .scroll-item .w3-container {
            min-height: 250px;
        }
        .scroll-buttons {
            text-align: center;
            margin-bottom: 16px;
        }
        .scroll-buttons .w3-button {
            margin: 0 5px;
        }
        .form-container {
            max-width: 500px;
            margin: auto;
            padding: 32px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }
        .form-container h1 {
            text-align: center;
            margin-bottom: 24px;
        }
        .form-container label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
        }
        .form-container input {
            width: 100%;
            padding: 12px;
            margin-bottom: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        .form-container button {
            width: 100%;
            padding: 12px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        .form-container button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>

<!-- Navbar -->
<div class="w3-top">
    <div class="w3-bar w3-black w3-card">
        <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
        <a href="{% url 'index' %}" class="w3-bar-item w3-button w3-padding-large">Accueil</a>
        <a href="#contact" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Contact</a>
        {% if user.is_authenticated %}
            <a href="{% url 'deconnexion' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Déconnexion</a>
        {% endif %}
        {% if not user.is_authenticated %}
            <a href="{% url 'connexion' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Connexion</a>
        {% endif %}
        <div class="w3-dropdown-hover w3-hide-small">
            <button class="w3-padding-large w3-button" title="More">Plus <i class="fa fa-caret-down"></i></button>     
            <div class="w3-dropdown-content w3-bar-block w3-card-4">
                <a href="{% url 'profile' %}" class="w3-bar-item w3-button">Profile</a>
                {% if user.is_authenticated and user.is_superuser %}
                    <a href="{% url 'Monitoring' %}" class="w3-bar-item w3-button">Statistiques</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- Page content -->
<div class="w3-content" style="max-width:2000px;margin-top:46px">

  <p style="padding-top: 2%;"  class="w3-wide w3-center"><u>Entrez un message ci-dessous pour que nous puissions prédire vos chances de réussite en formation !!</u></p>
    <!-- Formulaire de connexion -->
    <div class="form-container w3-card w3-light-grey">
        <h1>Prédiction</h1>
        <form method="POST">
          {% csrf_token %}
          <label for="name">Message:</label>
          <textarea class="w3-input w3-border" id="message" name="message" rows="5" required></textarea>
          <button type="submit">C'est parti!</button>
          {% if message_error %}
            <p style="color:red;">{{ message_error }}</p>
          {% endif %}
      </form>
    </div>
    {% if message_error %}
            <p style="color:red;">{{ message_error }}</p>
    {% endif %}
    {% if message %}
            <p style="color:red;">{{ message }}</p>
    {% endif %}
</br>
</br>

   
</div>
</br>
</br>

<div class="w3-row-padding" style="margin-left: 33%; text-align: center;">
    <h3 style="margin-right: 50%;";">Vous pouvez aussi choisir de nous déposer un document pour l'analyser!!</h3>
</br>
    <div class="w3-half">
        <input class="w3-input w3-border" type="file" name="Document">
    </div>
</div>
<img src="https://www.agvs-upsa.ch/system/files/agvs/News/2019/20191231_Werkstatt/handshake.jpg" class="w3-image w3-greyscale-min" style="width:100%;padding-top: 20%;">
    <!-- The Contact Section -->
    <div class="w3-container w3-content w3-padding-64" style="max-width:800px" id="contact">
        <h2 class="w3-wide w3-center">CONTACT</h2>
        <p class="w3-opacity w3-center"><i>Laissez-nous un commentaire !!</i></p>
        <div class="w3-row w3-padding-32">
            <div class="w3-col m6 w3-large w3-margin-bottom">
                <i class="fa fa-map-marker" style="width:30px"></i> Tours, 37000<br>
                <i class="fa fa-phone" style="width:30px"></i> Phone: +33 06151515<br>
                <i class="fa fa-envelope" style="width:30px"></i> Email: naoufelboutet2@gmail.com<br>
            </div>
            <div class="w3-col m6">
                <form id="contact-form" action="https://formspree.io/f/xdoqrnrv" method="POST">
                    <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
                        <div class="w3-half">
                            <input class="w3-input w3-border" type="text" placeholder="Nom" required name="Nom">
                        </div>
                        <div class="w3-half">
                            <input class="w3-input w3-border" type="text" placeholder="Email" required name="Email">
                        </div>
                    </div>
                    <input class="w3-input w3-border" type="text" placeholder="Message" required name="Message">
                    <button class="w3-button w3-black w3-section w3-right" type="submit">Envoyer</button>
                </form>
                <div id="confirmation-message" style="display: none;">Votre message a été envoyé avec succès.</div>
            </div>
        </div>
    </div>

    <!-- Image of location/map -->
  

    <!-- Footer -->
    <footer class="w3-container w3-padding-64 w3-center w3-opacity w3-light-grey w3-xlarge">
        <i class="fa fa-facebook-official w3-hover-opacity"></i>
        <i class="fa fa-instagram w3-hover-opacity"></i>
        <i class="fa fa-snapchat w3-hover-opacity"></i>
        <i class="fa fa-pinterest-p w3-hover-opacity"></i>
        <i class="fa fa-twitter w3-hover-opacity"></i>
        <i class="fa fa-linkedin w3-hover-opacity"></i>
        <p class="w3-medium">Powered by <a href="https://gretaformation.ac-orleans-tours.fr/greta-val-de-loire" target="_blank">DATA_P3_IA</a></p>
    </footer>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        document.getElementById("contact-form").addEventListener("submit", function(event) {
            // Affiche le message de confirmation
            document.getElementById("confirmation-message").style.display = "block";

            // Réinitialise le formulaire après 3 secondes
            setTimeout(function() {
                document.getElementById("confirmation-message").style.display = "none";
                document.getElementById("contact-form").reset();
            }, 3000);
        });
    });

    // Automatic Slideshow - change image every 4 seconds
    var myIndex = 0;
    carousel();

    function carousel() {
        var i;
        var x = document.getElementsByClassName("mySlides");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";  
        }
        myIndex++;
        if (myIndex > x.length) {myIndex = 1}    
        x[myIndex-1].style.display = "block";  
        setTimeout(carousel, 4000);
    }

    // Used to toggle the menu on small screens when clicking on the menu button
    function myFunction() {
        var x = document.getElementById("navDemo");
        if (x.className.indexOf("w3-show") == -1) {
            x.className += " w3-show";
        } else { 
            x.className = x.className.replace(" w3-show", "");
        }
    }

    // When the user clicks anywhere outside of the modal, close it
    var modal = document.getElementById('ticketModal');
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>

</body>
</html>

application/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>PrédiSchool</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
.mySlides {display: none}
.scroll-container {
    display: flex;
    overflow-x: auto;
    white-space: nowrap;
    margin: 0 -16px;
}
.scroll-item {
    display: inline-block;
    flex: 0 0 300px;
    margin: 0 8px;
    box-sizing: border-box;
   
}
.scroll-item .w3-container {
    min-height: 250px; /* Hauteur minimale pour uniformiser les encadrés */
}
.scroll-buttons {
    text-align: center;
    margin-bottom: 16px;
}
.scroll-buttons .w3-button {
    margin: 0 5px;
}
.user-info {
    background-color: #f2f2f2;
    padding: 20px;
    margin-bottom: 20px;
    border-radius: 5px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

.user-info p {
    margin: 5px 0;
    font-size: 16px;
}

.user-info p:first-child {
    font-size: 20px;
    font-weight: bold;
    margin-top: 0;
}

</style>
</head>
<body>

<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="{% url 'index' %}" class="w3-bar-item w3-button w3-padding-large">Accueil</a>
    <a href="{% url 'prediction' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Prédiction</a>
    <a href="#contact" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Contact</a>
    {% if user.is_authenticated %}
        <a href="{% url 'deconnexion' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Déconnexion</a>
    {% endif %}
    {% if not user.is_authenticated %}
        <a href="{% url 'connexion' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Connexion</a>
    {% endif %}
    {% if user.is_authenticated %}
    <div class="w3-dropdown-hover w3-hide-small">
      <button class="w3-padding-large w3-button" title="More">Plus <i class="fa fa-caret-down"></i></button>     
      <div class="w3-dropdown-content w3-bar-block w3-card-4">
        <a href="#" class="w3-bar-item w3-button">Profile</a>
        {% if user.is_authenticated and user.is_superuser %}
            <a href="{% url 'Monitoring' %}" class="w3-bar-item w3-button">Statistiques</a>
        {% endif %}
        {% endif %}
      </div>
    </div>
    
  </div>
</div>

<!-- Page content -->
<div class="w3-content" style="max-width:2000px;margin-top:46px">
    <div class="user-info">
        <h2 style="text-align: center;">Vos informations utilisateur {{ first_name }}!</h2>
        <p><strong>Nom d'utilisateur:</strong> {{ username }}</p>
        <p><strong>Email:</strong> {{ email }}</p>
        <p><strong>Prénom:</strong> {{ first_name }}</p>
        <p><strong>Nom:</strong> {{ last_name }}</p>
        <p><strong>Ville:</strong> {{ city }}</p>
        <p><strong>Date de naissance:</strong> {{ birth_day }}</p>
    </div>

  <!-- The Contact Section -->
  <div class="w3-container w3-content w3-padding-64" style="max-width:800px" id="contact">
    <h2 class="w3-wide w3-center">CONTACT</h2>
    <p class="w3-opacity w3-center"><i>Un souci? Contactez-nous!</i></p>
    <div class="w3-row w3-padding-32">
      <div class="w3-col m6 w3-large w3-margin-bottom">
        <i class="fa fa-map-marker" style="width:30px"></i> Tours, 37000<br>
        <i class="fa fa-phone" style="width:30px"></i> Phone: +33 06151515<br>
        <i class="fa fa-envelope" style="width:30px"> </i> Email: naoufelboutet2@gmail.com<br>
      </div>
      <div class="w3-col m6">
        <form id="contact-form" action="https://formspree.io/f/xdoqrnrv" method="POST">
          <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
            <div class="w3-half">
              <input class="w3-input w3-border" type="text" placeholder="Name" required name="Nom">
            </div>
            <div class="w3-half">
              <input class="w3-input w3-border" type="text" placeholder="Email" required name="Email">
            </div>
          </div>
          <input class="w3-input w3-border" type="text" placeholder="Message" required name="Message">
          <button class="w3-button w3-black w3-section w3-right" type="submit">Envoyer</button>
        </form>
        <div id="confirmation-message" style="display: none;">Votre message a été envoyé avec succès.</div>
      </div>
    </div>
  </div>
 
 
<!-- End Page Content -->
</div>

<!-- Image of location/map -->
<img src="https://www.agvs-upsa.ch/system/files/agvs/News/2019/20191231_Werkstatt/handshake.jpg" class="w3-image w3-greyscale-min" style="width:100%">

<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity w3-light-grey w3-xlarge">
  <i class="fa fa-facebook-official w3-hover-opacity"></i>
  <i class="fa fa-instagram w3-hover-opacity"></i>
  <i class="fa fa-snapchat w3-hover-opacity"></i>
  <i class="fa fa-pinterest-p w3-hover-opacity"></i>
  <i class="fa fa-twitter w3-hover-opacity"></i>
  <i class="fa fa-linkedin w3-hover-opacity"></i>
  <p class="w3-medium">Powered by <a href="https://gretaformation.ac-orleans-tours.fr/greta-val-de-loire" target="_blank">DATA_P3_IA</a></p>
</footer>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    document.getElementById("contact-form").addEventListener("submit", function(event) {
      // Affiche le message de confirmation
      document.getElementById("confirmation-message").style.display = "block";

      // Réinitialise le formulaire après 3 secondes
      setTimeout(function() {
        document.getElementById("confirmation-message").style.display = "none";
        document.getElementById("contact-form").reset();
      }, 3000);
    });
  });
</script>
<script>
// Automatic Slideshow - change image every 4 seconds
var myIndex = 0;
carousel();

function carousel() {
  var i;
  var x = document.getElementsByClassName("mySlides");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";  
  }
  myIndex++;
  if (myIndex > x.length) {myIndex = 1}    
  x[myIndex-1].style.display = "block";  
  setTimeout(carousel, 4000);    
}

// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}

// When the user clicks anywhere outside of the modal, close it
var modal = document.getElementById('ticketModal');
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>

</body>
</html>



   

authentification/templates/inscription.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Inscription</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {
    font-family: "Lato", sans-serif;
}
.mySlides {
    display: none;
}
.scroll-container {
    display: flex;
    overflow-x: auto;
    white-space: nowrap;
    margin: 0 -16px;
}
.scroll-item {
    display: inline-block;
    flex: 0 0 300px;
    margin: 0 8px;
    box-sizing: border-box;
}
.scroll-item .w3-container {
    min-height: 250px; /* Hauteur minimale pour uniformiser les encadrés */
}
.scroll-buttons {
    text-align: center;
    margin-bottom: 16px;
}
.scroll-buttons .w3-button {
    margin: 0 5px;
}
.form-container {
    max-width: 500px;
    margin: auto;
    padding: 32px;
    border: 1px solid #ccc;
    border-radius: 10px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}
.form-container h1 {
    text-align: center;
    margin-bottom: 24px;
}
.form-container label {
    display: block;
    margin-bottom: 8px;
    font-weight: bold;
}
.form-container input {
    width: 100%;
    padding: 12px;
    margin-bottom: 16px;
    border: 1px solid #ccc;
    border-radius: 4px;
}
.form-container button {
    width: 100%;
    padding: 12px;
    background-color: #4CAF50;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}
.form-container button:hover {
    background-color: #45a049;
}
</style>
</head>
<body>

<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="{% url 'index' %}" class="w3-bar-item w3-button w3-padding-large">Accueil</a>
    <a href="{% url 'connexion' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Connexion</a>
    
  </div>
</div>

<!-- Page content -->
<div class="w3-content" style="max-width:2000px;margin-top:46px">

  <!-- Formulaire de connexion -->
  <div class="form-container w3-card w3-light-grey">
    <h1>Inscription</h1>
    <form method="POST" onsubmit="return validateForm()">
        {% csrf_token %}
        <label for="id_username">Nom d'utilisateur:</label>
        <input type="text" name="username" required id="id_username">
        
        <label for="id_password1">Mot de passe:</label>
        <input type="password" name="password1" required id="id_password1">
        
        <label for="id_password2">Confirmation mot de passe:</label>
        <input type="password" name="password2" required id="id_password2">
        
        <label for="id_email">Email:</label>
        <input type="email" name="email" required id="id_email">
        
        <label for="id_first_name">Prénom:</label>
        <input type="text" name="first_name" required id="id_first_name">
        
        <label for="id_last_name">Nom:</label>
        <input type="text" name="last_name" required id="id_last_name">

        <label for="City">Ville:</label>
        <input type="text" name="city" required id="id_city">

        <label for="birth_day">Année de naissance:</label>
        <input type="date" name="birth_day" required id="id_birth_day">
        
        <button type="submit">S'inscrire</button>
        {% if error_message %}
            <p style="color:red;">{{ error_message }}</p>
        {% endif %}
        <p>Vous avez déjà un compte? <a href="{% url 'inscription' %}">Connectez-vous!</a></p>
    </form>
  </div>

<!-- End Page Content -->
</div>
<script>
// Automatic Slideshow - change image every 4 seconds
var myIndex = 0;
carousel();

function carousel() {
  var i;
  var x = document.getElementsByClassName("mySlides");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";  
  }
  myIndex++;
  if (myIndex > x.length) {myIndex = 1}    
  x[myIndex-1].style.display = "block";  
  setTimeout(carousel, 4000);    
}

// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}

// When the user clicks anywhere outside of the modal, close it
var modal = document.getElementById('ticketModal');
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>

</body>
</html>